import {createFileRoute} from "@tanstack/react-router";
type Update={update_id:number;message?:{message_id:number;text?:string;chat:{id:number;type:string};from?:{id:number}}};
async function send(chatId:number,text:string){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error("Telegram bot is not configured");const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:text.slice(0,4000)})});if(!r.ok)throw new Error(`Telegram send failed ${r.status}`);}
export const Route=createFileRoute("/api/telegram/webhook")({server:{handlers:{POST:async({request})=>{
  if(!process.env.TELEGRAM_WEBHOOK_SECRET||request.headers.get("x-telegram-bot-api-secret-token")!==process.env.TELEGRAM_WEBHOOK_SECRET)return new Response("Forbidden",{status:403});
  const update=await request.json() as Update,{supabaseAdmin:raw}=await import("@/integrations/supabase/client.server"),db=raw as any;
  const [{answerKi},{hashToken}]=await Promise.all([import("@/lib/ki-orchestrator.server"),import("@/lib/auth/primitives")]);
  const inserted=await db.from("ki_telegram_updates").insert({update_id:update.update_id});if(inserted.error?.code==="23505")return new Response("OK");
  const msg=update.message;if(!msg?.text||msg.chat.type!=="private"||!msg.from)return new Response("OK");
  try{
    const start=msg.text.match(/^\/start\s+([A-Z0-9_-]+)/i);
    if(start){const{data:links}=await db.from("telegram_connections").select("id,user_id,link_code_hash,link_code_expires_at").is("linked_at",null);const link=(links??[]).find((l:any)=>l.link_code_hash===hashToken(start[1].toUpperCase())&&new Date(l.link_code_expires_at).getTime()>Date.now());if(!link)await send(msg.chat.id,"This linking code is invalid or expired. Create a new code in KI Operator.");else{await db.from("telegram_connections").update({telegram_user_id:msg.from.id,chat_id:msg.chat.id,linked_at:new Date().toISOString(),link_code_hash:null,link_code_expires_at:null}).eq("id",link.id);await send(msg.chat.id,"Telegram is linked. Ask about positions or use /status, /positions, /market, /explain, /mute, /settings.");}await db.from("ki_telegram_updates").update({processed_at:new Date().toISOString()}).eq("update_id",update.update_id);return new Response("OK");}
    const{data:connection}=await db.from("telegram_connections").select("user_id,enabled").eq("telegram_user_id",msg.from.id).eq("chat_id",msg.chat.id).maybeSingle();if(!connection?.enabled){await send(msg.chat.id,"Link Telegram from KI Operator first.");return new Response("OK");}
    let prompt=msg.text;if(["/status","/positions"].includes(prompt))prompt="Give a concise status of every open position and current recommended action.";if(prompt==="/market")prompt="Summarize current regimes, feed health, and evidence-backed corridors.";if(prompt==="/explain")prompt="Explain the latest recommendation and invalidation conditions.";if(prompt==="/mute"){await db.from("ki_strategy_settings").upsert({user_id:connection.user_id,muted_until:new Date(Date.now()+28_800_000).toISOString()},{onConflict:"user_id"});await send(msg.chat.id,"Alerts muted for 8 hours. Chat remains available.");return new Response("OK");}if(prompt==="/settings")prompt="Summarize my strategy settings and how to change them in the web app.";
    const{data:conversation}=await db.from("ki_conversations").upsert({user_id:connection.user_id,channel:"telegram",external_thread_id:String(msg.chat.id),updated_at:new Date().toISOString()},{onConflict:"user_id,channel,external_thread_id"}).select("id").single();if(conversation)await db.from("ki_conversation_messages").insert({conversation_id:conversation.id,role:"user",content:msg.text,external_message_id:String(msg.message_id)});const answer=await answerKi(connection.user_id,prompt);await send(msg.chat.id,answer);if(conversation)await db.from("ki_conversation_messages").insert({conversation_id:conversation.id,role:"assistant",content:answer});await db.from("ki_telegram_updates").update({processed_at:new Date().toISOString()}).eq("update_id",update.update_id);
  }catch(error){await db.from("ki_telegram_updates").update({error_message:error instanceof Error?error.message:String(error)}).eq("update_id",update.update_id);return new Response("Retry",{status:500});}return new Response("OK");
}}}});
